server:
  port: ${PORT}

spring:
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: never 
      schema-locations: classpath:schema.sql 
      data-locations: classpath:data.sql 
  logging:
    level:
      org.springframework.r2dbc: DEBUG
      org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

ai:
  gemini:
    api-key: ${GEMINI_APIKEY}
    base-url: ${GEMINI_URL}
    model: ${GEMINI_MODEL}

  huggingface:
    api-key: ${HUGGINGFACE_APIKEY}
    base-url: ${HUGGINGFACE_URL}
    model: ${HUGGINGFACE_MODEL}
    