# kubectl apply -f josemaria-valenzuela-41-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: josemaria-valenzuela-41-secret
  namespace: josemaria-valenzuela-41-namespace
type: Opaque
data:
  PORT: ODg4NQ== # en Base64
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXN0ZWVwLWZpZWxkLWFuaHl6YTM0LXBvb2xlci5jLTYudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvam9zZW1hcmlhX3ZhbGVuenVlbGFfNDE/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl   # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy  # en Base64
  DATABASE_PASSWORD: bnBnX0o1bGNnbkFMam9mNw==  # en Base64
  GEMINI_URL: aHR0cHM6Ly9nZW5lcmF0aXZlbGFuZ3VhZ2UuZ29vZ2xlYXBpcy5jb20vdjFiZXRh   # en Base64
  GEMINI_APIKEY: QUl6YVN5QVFCTF9USTI3MnhBbWxHUmp0UFIwUnprc3dkclYwU3JN   # en Base64
  GEMINI_MODEL: Z2VtaW5pLTIuNS1mbGFzaA==  
  HUGGINGFACE_URL: aHR0cHM6Ly9yb3V0ZXIuaHVnZ2luZ2ZhY2UuY28vaGYtaW5mZXJlbmNlL21vZGVscw==   # en Base64
  HUGGINGFACE_APIKEY: aGZfc2NTRnFGZWxjeWFuUVNRVnZIRkZ6T0ZCWEVoVFpzZlp5WA==   # en Base64
  HUGGINGFACE_MODEL: ZmFjZWJvb2svYmFydC1sYXJnZS1tbmxp
# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode